feat. add other-plugins-events attribute
BG-Software-LLC/WildTools pull request #61
Opened 2021-08-04 13:24 UTC by nivcoo

Hello, i've added attribut to call event of specific plugin depending on the item. Let me know if you want to change anything

2021-08-05 09:48 UTC, OmerBenGera commented
I told you whats the issue with that in the ticket.
Closing this for now, you are more than welcome to make a new PR with another implementation.
Thanks for the time spending on this tho :)

2021-08-05 19:31 UTC, nivcoo commented
Have you see my comment about this commit ?

2021-08-05 20:54 UTC, OmerBenGera commented
I will look into the code when I am at home.
Thanks for contributing!

2021-08-06 09:07 UTC, nivcoo commented
> I will look into the code when I am at home.
> Thanks for contributing!

Thx, there is surely some optimization to do but the idea behind is present :p

2021-08-06 10:15 UTC, nivcoo commented
I've move the load of otherEvents to be only load once

2021-08-14 14:00 UTC, OmerBenGera requested changes

2021-08-14 14:00 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildtools/handlers/EventsHandler.java
> +    public void loadOtherPlugins(List<String> otherPlugins, List<CachedListenerMethod> otherPluginsBreakMethods) {
Is otherPluginsBreakMethods necessary for the method?

2021-08-14 14:00 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildtools/objects/tools/WTool.java
> +    public Set<String> otherPluginsEvents() { return otherPluginsEvents; }
Don't use inline methods.

2021-08-15 14:35 UTC, nivcoo commented on src/main/java/com/bgsoftware/wildtools/handlers/EventsHandler.java
> +            List<CachedListenerMethod> otherPluginsMethods = otherPluginsBreakMethodsTools.get(tool);
I don't understand exactly what you mean here

2021-08-21 16:05 UTC, nivcoo commented
Any news ?

2021-09-12 20:30 UTC, nivcoo commented
Any news ?

2021-09-25 16:53 UTC, nivcoo commented
Any news ?

2021-09-26 16:18 UTC, OmerBenGera commented
> Any news ?

I totally forgot about that, I am so sorry you had to wait that long.
I will look into that tomorrow.

2021-09-26 16:19 UTC, nivcoo commented
Thx

2021-09-27 10:36 UTC, OmerBenGera approved these changes

2021-09-27 10:36 UTC, OmerBenGera requested changes
Should be merged to dev, not to master

2021-09-27 10:41 UTC, nivcoo commented
Can you check my last changes for conflicts ? i think it's good

2021-09-27 11:00 UTC, nivcoo commented
Sorry for lot of commit :/ let me know if it's good idk how works merge like that :/

2021-11-07 14:01 UTC, nivcoo commented
Any news ?

2021-11-13 15:01 UTC, merged